name: app
description: Test Ideas App
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  design_system:
    path: ../design_system
  flutter_riverpod: ^2.5.1
  mix: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0